version: "3.7"

volumes:
  mivolumen:


services:
  python:
    image: ${DOCKER_REPO:-kontinu}/foo:bar

    environment:
      - REDIS_HOST=redis
      - FOO=${FOO}
    build:
      context: src/python
    deploy:
      replicas: 3
    ports:
      - 8080:8080

  nodejs:
    image: ${DOCKER_REPO:-kontinu}/nodejs-expert:v1.1
    build:
      context: src/nodejs
    deploy:
      replicas: 2
    ports:
      - 8081:8080

  go:
    image: ${DOCKER_REPO:-kontinu}/go-expert:v1.0
    build:
      context: src/go
    deploy:
      replicas: 5
    ports:
      - 8082:8080

  redis:
    image: redis:alpine
    deploy:
      replicas: 1

